// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuIZ2vkq7QNilG1jnqx2Fg8B545OG02iA',
    appId: '1:237177868286:web:736b1932108f95e038baaf',
    messagingSenderId: '237177868286',
    projectId: 'haohsing-374de',
    authDomain: 'haohsing-374de.firebaseapp.com',
    storageBucket: 'haohsing-374de.appspot.com',
    measurementId: 'G-BYNES4VW30',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxqcCKYbBr3iWA_AZF1F0riL0aQmSSEN4',
    appId: '1:237177868286:android:2fb50502d8b0090e38baaf',
    messagingSenderId: '237177868286',
    projectId: 'haohsing-374de',
    storageBucket: 'haohsing-374de.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBruvd1lNj2Bt_20Zvw1Qc8U0PYKUiFXbI',
    appId: '1:237177868286:ios:bc3f9dc12cb2c16a38baaf',
    messagingSenderId: '237177868286',
    projectId: 'haohsing-374de',
    storageBucket: 'haohsing-374de.appspot.com',
    androidClientId: '237177868286-0ugdmc8sofqvnoeahso2rnkmf4ndqael.apps.googleusercontent.com',
    iosClientId: '237177868286-gjcg1u2jnfbr55trcp9qr2ojf0dpt8d7.apps.googleusercontent.com',
    iosBundleId: 'com.clockworkorange.haohsing',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBruvd1lNj2Bt_20Zvw1Qc8U0PYKUiFXbI',
    appId: '1:237177868286:ios:4fa1585afe79e1cb38baaf',
    messagingSenderId: '237177868286',
    projectId: 'haohsing-374de',
    storageBucket: 'haohsing-374de.appspot.com',
    androidClientId: '237177868286-0ugdmc8sofqvnoeahso2rnkmf4ndqael.apps.googleusercontent.com',
    iosClientId: '237177868286-jp5sqvgom42rkbapb0i8ei7jlppp68gd.apps.googleusercontent.com',
    iosBundleId: 'com.example.haohsingFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCuIZ2vkq7QNilG1jnqx2Fg8B545OG02iA',
    appId: '1:237177868286:web:a947d9f347f5ba9138baaf',
    messagingSenderId: '237177868286',
    projectId: 'haohsing-374de',
    authDomain: 'haohsing-374de.firebaseapp.com',
    storageBucket: 'haohsing-374de.appspot.com',
    measurementId: 'G-LM1RW5YHL7',
  );
}
